; ============================================================================
; test_wrap_consolidation.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_wrap_consolidation.asm WRAPTEST
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_wrap_consolidation.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_wrap_consolidation.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though 16 real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ; (Superseded-but-harmless as of BASIC_COMMAND_LOOP's own later
    ; fix, which now counts real existing statements itself on every
    ; entry regardless of how they got into memory — this line's own
    ; value gets silently overwritten with the same correct count
    ; moments later. Left in for consistency with the tested,
    ; delivered state rather than removed.)
    ld   hl, 16
    ld   (CUR_EDIT_INDEX), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $49,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$45,$53,$54,$20,$57,$52
    DB   $41,$50,$20,$4F,$4E,$45,$20,$54,$48,$49,$53,$20,$53,$48,$4F,$55
    DB   $4C,$44,$20,$57,$52,$41,$50,$20,$54,$4F,$20,$41,$20,$53,$45,$43
    DB   $4F,$4E,$44,$20,$52,$4F,$57,$20,$4E,$49,$43,$45,$4C,$59,$20,$52
    DB   $49,$47,$48,$54,$20,$48,$45,$52,$45,$22,$0D,$06,$00,$41,$20,$3D
    DB   $20,$31,$0D,$64,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$45,$53,$54
    DB   $20,$57,$52,$41,$50,$20,$54,$57,$4F,$20,$41,$4E,$4F,$54,$48,$45
    DB   $52,$20,$4C,$4F,$4E,$47,$20,$53,$54,$41,$54,$45,$4D,$45,$4E,$54
    DB   $20,$54,$48,$41,$54,$20,$53,$48,$4F,$55,$4C,$44,$20,$41,$4C,$53
    DB   $4F,$20,$57,$52,$41,$50,$20,$41,$43,$52,$4F,$53,$53,$20,$4D,$55
    DB   $4C,$54,$49,$50,$4C,$45,$20,$52,$4F,$57,$53,$20,$46,$4F,$52,$20
    DB   $54,$45,$53,$54,$49,$4E,$47,$22,$0D,$06,$00,$42,$20,$3D,$20,$32
    DB   $0D,$5F,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$48,$49,$53,$20,$53
    DB   $54,$52,$49,$4E,$47,$20,$49,$53,$20,$4E,$4F,$54,$20,$43,$4C,$4F
    DB   $53,$45,$44,$20,$41,$4E,$44,$20,$53,$48,$4F,$55,$4C,$44,$20,$54
    DB   $52,$49,$47,$47,$45,$52,$20,$41,$4E,$20,$45,$52,$52,$4F,$52,$20
    DB   $46,$4C,$41,$47,$20,$41,$43,$52,$4F,$53,$53,$20,$4D,$55,$4C,$54
    DB   $49,$50,$4C,$45,$20,$57,$52,$41,$50,$50,$45,$44,$20,$52,$4F,$57
    DB   $53,$0D,$06,$00,$43,$20,$3D,$20,$33,$0D,$14,$00,$50,$52,$49,$4E
    DB   $54,$20,$22,$53,$48,$4F,$52,$54,$20,$41,$47,$41,$49,$4E,$22,$0D
    DB   $5B,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$45,$53,$54,$20,$57,$52
    DB   $41,$50,$20,$54,$48,$52,$45,$45,$20,$59,$45,$54,$20,$41,$4E,$4F
    DB   $54,$48,$45,$52,$20,$4C,$4F,$4E,$47,$20,$57,$52,$41,$50,$50,$49
    DB   $4E,$47,$20,$4C,$49,$4E,$45,$20,$54,$4F,$20,$48,$45,$4C,$50,$20
    DB   $50,$55,$53,$48,$20,$54,$48,$45,$20,$54,$4F,$54,$41,$4C,$20,$52
    DB   $4F,$57,$20,$43,$4F,$55,$4E,$54,$20,$55,$50,$22,$0D,$06,$00,$44
    DB   $20,$3D,$20,$34,$0D,$60,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$45
    DB   $53,$54,$20,$57,$52,$41,$50,$20,$46,$4F,$55,$52,$20,$4D,$4F,$52
    DB   $45,$20,$57,$52,$41,$50,$50,$49,$4E,$47,$20,$43,$4F,$4E,$54,$45
    DB   $4E,$54,$20,$48,$45,$52,$45,$20,$54,$4F,$20,$43,$4F,$4E,$54,$49
    DB   $4E,$55,$45,$20,$50,$41,$44,$44,$49,$4E,$47,$20,$4F,$55,$54,$20
    DB   $54,$48,$45,$20,$56,$49,$53,$49,$42,$4C,$45,$20,$52,$4F,$57,$20
    DB   $43,$4F,$55,$4E,$54,$22,$0D,$06,$00,$45,$20,$3D,$20,$35,$0D,$5C
    DB   $00,$50,$52,$49,$4E,$54,$20,$22,$41,$4E,$4F,$54,$48,$45,$52,$20
    DB   $55,$4E,$43,$4C,$4F,$53,$45,$44,$20,$53,$54,$52,$49,$4E,$47,$20
    DB   $48,$45,$52,$45,$20,$54,$4F,$20,$47,$49,$56,$45,$20,$41,$20,$53
    DB   $45,$43,$4F,$4E,$44,$20,$45,$52,$52,$4F,$52,$20,$4C,$49,$4E,$45
    DB   $20,$46,$4F,$52,$20,$54,$45,$53,$54,$49,$4E,$47,$20,$54,$48,$41
    DB   $54,$20,$46,$49,$58,$49,$4E,$47,$20,$4F,$4E,$45,$0D,$5E,$00,$50
    DB   $52,$49,$4E,$54,$20,$22,$54,$45,$53,$54,$20,$57,$52,$41,$50,$20
    DB   $46,$49,$56,$45,$20,$53,$54,$49,$4C,$4C,$20,$4D,$4F,$52,$45,$20
    DB   $57,$52,$41,$50,$50,$49,$4E,$47,$20,$54,$45,$58,$54,$20,$4E,$45
    DB   $45,$44,$45,$44,$20,$54,$4F,$20,$47,$45,$54,$20,$50,$41,$53,$54
    DB   $20,$54,$48,$45,$20,$54,$57,$45,$4E,$54,$59,$20,$54,$48,$52,$45
    DB   $45,$20,$52,$4F,$57,$20,$4C,$49,$4D,$49,$54,$22,$0D,$06,$00,$46
    DB   $20,$3D,$20,$36,$0D,$60,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$45
    DB   $53,$54,$20,$57,$52,$41,$50,$20,$53,$49,$58,$20,$46,$49,$4E,$41
    DB   $4C,$20,$4C,$4F,$4E,$47,$20,$57,$52,$41,$50,$50,$49,$4E,$47,$20
    DB   $4C,$49,$4E,$45,$20,$54,$4F,$20,$44,$45,$46,$49,$4E,$49,$54,$45
    DB   $4C,$59,$20,$50,$55,$53,$48,$20,$54,$48,$49,$53,$20,$50,$41,$53
    DB   $54,$20,$54,$48,$45,$20,$53,$43,$52,$4F,$4C,$4C,$20,$42,$4F,$55
    DB   $4E,$44,$41,$52,$59,$22,$0D,$12,$00,$50,$52,$49,$4E,$54,$20,$22
    DB   $4C,$41,$53,$54,$20,$4C,$49,$4E,$45,$22,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    INCLUDE "kernel/storage/storage.asm"

    DS   $4000 - $, $FF

    SAVEBIN "test_wrap_consolidation.bin", $0000, $4000
