; ============================================================================
; test_full_regr2.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_full_regr2.asm TFR2
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_full_regr2.asm
; Run: (needs a real exrom.bin now -- see rom/exrom_build.asm -- the
; checker AND storage this file's own basic.asm INCLUDE pulls in both
; page there unconditionally on RUN/SAVE/LOAD; a placeholder rom1.bin
; pages into garbage)
;   sjasmplus rom/exrom_build.asm
;   fuse --machine ts2068 --rom-ts2068-0 test_full_regr2.bin --rom-ts2068-1 exrom.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"
    DEFINE EXROM_JUMPTABLE_HOME_SIDE     ; must precede the INCLUDE
                                         ; below — selects the `jp`-
                                         ; emitting branch of KTAB_LIST
                                         ; rather than the EQU-emitting
                                         ; one exrom_build.asm gets
    INCLUDE "include/exrom_jumptable.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START

    DS   $0028 - $, $FF
; ---- RST 28: calculator engine entry point -- matches rom/test_basic.
; asm's own wiring exactly (added here 2026-08-22 after a preload-
; harness "hang" investigating a SIN()/PI() bug turned out to be THIS
; gap instead: with no RST_28 defined, the DS padding above used to
; fill $0028 with $FF -- opcode for RST $38 -- so any `rst $28` in a
; harness generated before this fix silently jumped into the keyboard
; ISR entry instead of the calculator engine, not a real product bug).
; MUST be a bare `jp`, not `call` -- see basic/basic.asm's CALC_ENTRY_
; TRAMPOLINE header for why (RST pushed the literal-op byte stream's
; address as the return address; the calculator needs that exact value
; untouched on top of the stack). ----
RST_28:
    jp   CALC_ENTRY_TRAMPOLINE

    DS   $0038 - $, $FF
; ---- RST 38 / IM 1 maskable interrupt entry point ----
; Same real keyboard-scan ISR as rom/test_basic.asm -- see kernel/
; interrupt/interrupt.asm's own header.
RST_38:
    call KBD_ISR_TICK
    ei
    reti

; ---- EXROM call table -- single source of truth is include/
; exrom_jumptable.inc's own KTAB_LIST macro; mirrors rom/test_basic.asm's
; own layout exactly (see that file if this drifts again). Needed here
; because basic.asm's BASIC_RUN calls BASIC_FULL_CHECK_EXROM
; unconditionally -- without this table (and a real exrom.bin
; paired via --rom-ts2068-1) the checker pages into garbage the moment
; RUN is pressed. ----
    ORG  KTAB_BASE
    KTAB_LIST
    ASSERT $ <= KTAB_END
    DB   KTAB_MAGIC

    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT
    call KBD_ISR_INIT                ; kernel/interrupt -- must run
                                     ; before the EI below

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though 46 real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ; (Superseded-but-harmless as of BASIC_COMMAND_LOOP's own later
    ; fix, which now counts real existing statements itself on every
    ; entry regardless of how they got into memory — this line's own
    ; value gets silently overwritten with the same correct count
    ; moments later. Left in for consistency with the tested,
    ; delivered state rather than removed.)
    ld   hl, 46
    ld   (CUR_EDIT_INDEX), hl

    im   1
    ei                                ; real interrupts now on -- see
                                     ; rom/test_basic.asm's own COLD_
                                     ; START comment for why

    call GFX_CLS
    call BASIC_RESET_TEXT_ATTR
    ld   a, 6
    call GFX_SET_BORDER
    call BASIC_RUN
    ld   hl, (CHECK_ERROR_COUNT)
    ld   a, h
    or   l
    jr   z, .hang
    ld   a, 5
    call GFX_SET_BORDER
.hang:
    jr   .hang

PRELOAD_DATA:
    DB   $0A,$00,$41,$20,$3D,$20,$35,$30,$31,$37,$36,$0D,$0A,$00,$50,$4F
    DB   $4B,$45,$20,$41,$2C,$34,$32,$0D,$0C,$00,$42,$20,$3D,$20,$50,$45
    DB   $45,$4B,$28,$41,$29,$0D,$1B,$00,$49,$46,$20,$42,$20,$3D,$20,$34
    DB   $32,$20,$54,$48,$45,$4E,$20,$47,$4F,$54,$4F,$20,$70,$6F,$6B,$65
    DB   $6F,$6B,$0D,$09,$00,$42,$4F,$52,$44,$45,$52,$20,$32,$0D,$05,$00
    DB   $53,$54,$4F,$50,$0D,$08,$00,$70,$6F,$6B,$65,$6F,$6B,$3A,$0D,$0B
    DB   $00,$43,$20,$3D,$20,$46,$52,$45,$45,$28,$29,$0D,$1C,$00,$49,$46
    DB   $20,$43,$20,$3D,$20,$30,$20,$54,$48,$45,$4E,$20,$47,$4F,$54,$4F
    DB   $20,$66,$72,$65,$65,$66,$61,$69,$6C,$0D,$0C,$00,$47,$4F,$54,$4F
    DB   $20,$66,$72,$65,$65,$6F,$6B,$0D,$0A,$00,$66,$72,$65,$65,$66,$61
    DB   $69,$6C,$3A,$0D,$09,$00,$42,$4F,$52,$44,$45,$52,$20,$32,$0D,$05
    DB   $00,$53,$54,$4F,$50,$0D,$08,$00,$66,$72,$65,$65,$6F,$6B,$3A,$0D
    DB   $0A,$00,$44,$20,$3D,$20,$35,$30,$31,$39,$32,$0D,$0A,$00,$50,$4F
    DB   $4B,$45,$20,$44,$2C,$33,$33,$0D,$0C,$00,$50,$4F,$4B,$45,$20,$44
    DB   $2B,$31,$2C,$34,$39,$0D,$0D,$00,$50,$4F,$4B,$45,$20,$44,$2B,$32
    DB   $2C,$32,$31,$30,$0D,$0D,$00,$50,$4F,$4B,$45,$20,$44,$2B,$33,$2C
    DB   $32,$30,$31,$0D,$0B,$00,$45,$20,$3D,$20,$55,$53,$52,$28,$44,$29
    DB   $0D,$1D,$00,$49,$46,$20,$45,$20,$3D,$20,$35,$33,$38,$30,$39,$20
    DB   $54,$48,$45,$4E,$20,$47,$4F,$54,$4F,$20,$75,$73,$72,$6F,$6B,$0D
    DB   $09,$00,$42,$4F,$52,$44,$45,$52,$20,$32,$0D,$05,$00,$53,$54,$4F
    DB   $50,$0D,$07,$00,$75,$73,$72,$6F,$6B,$3A,$0D,$0C,$00,$52,$41,$4E
    DB   $44,$4F,$4D,$49,$53,$45,$20,$35,$0D,$0E,$00,$46,$20,$3D,$20,$52
    DB   $4E,$44,$28,$31,$30,$30,$30,$29,$0D,$0C,$00,$52,$41,$4E,$44,$4F
    DB   $4D,$49,$53,$45,$20,$35,$0D,$0E,$00,$47,$20,$3D,$20,$52,$4E,$44
    DB   $28,$31,$30,$30,$30,$29,$0D,$1A,$00,$49,$46,$20,$46,$20,$3D,$20
    DB   $47,$20,$54,$48,$45,$4E,$20,$47,$4F,$54,$4F,$20,$72,$61,$6E,$64
    DB   $6F,$6B,$0D,$09,$00,$42,$4F,$52,$44,$45,$52,$20,$32,$0D,$05,$00
    DB   $53,$54,$4F,$50,$0D,$08,$00,$72,$61,$6E,$64,$6F,$6B,$3A,$0D,$0D
    DB   $00,$47,$4F,$53,$55,$42,$20,$73,$75,$62,$6F,$6E,$65,$0D,$1B,$00
    DB   $49,$46,$20,$48,$20,$3D,$20,$31,$20,$54,$48,$45,$4E,$20,$47,$4F
    DB   $54,$4F,$20,$67,$6F,$73,$75,$62,$6F,$6B,$0D,$09,$00,$42,$4F,$52
    DB   $44,$45,$52,$20,$32,$0D,$05,$00,$53,$54,$4F,$50,$0D,$09,$00,$67
    DB   $6F,$73,$75,$62,$6F,$6B,$3A,$0D,$0B,$00,$50,$52,$49,$4E,$54,$20
    DB   $50,$49,$28,$29,$0D,$0E,$00,$50,$52,$49,$4E,$54,$20,$52,$41,$44
    DB   $28,$39,$30,$29,$0D,$0D,$00,$50,$52,$49,$4E,$54,$20,$44,$45,$47
    DB   $28,$31,$29,$0D,$08,$00,$50,$41,$55,$53,$45,$20,$35,$0D,$09,$00
    DB   $42,$4F,$52,$44,$45,$52,$20,$34,$0D,$05,$00,$53,$54,$4F,$50,$0D
    DB   $08,$00,$73,$75,$62,$6F,$6E,$65,$3A,$0D,$06,$00,$48,$20,$3D,$20
    DB   $31,$0D,$07,$00,$52,$45,$54,$55,$52,$4E,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here -- SAVE/LOAD
    ; now lives in EXROM (rom/exrom_storage.asm) and basic.asm's
    ; BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed address; this
    ; template never defined STORAGE_MATH_MULTIPLY16/STORAGE_MATH_DIVIDE16
    ; (storage.asm's required pre-INCLUDE EQUs), so including it here would
    ; never have assembled. See rom/test_basic.asm.
    INCLUDE "kernel/interrupt/interrupt.asm"
    INCLUDE "kernel/bank/bank.asm"

    DS   $4000 - $, $FF

    SAVEBIN "test_full_regr2.bin", $0000, $4000
