; ============================================================================
; test_preload_sprite_demo.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_sprite_demo.asm SPRITE_DEMO
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_sprite_demo.asm
; Run: (needs a real exrom.bin now -- see rom/exrom_build.asm -- the
; checker AND storage this file's own basic.asm INCLUDE pulls in both
; page there unconditionally on RUN/SAVE/LOAD; a placeholder rom1.bin
; pages into garbage)
;   sjasmplus rom/exrom_build.asm
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_sprite_demo.bin --rom-ts2068-1 exrom.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"
    DEFINE EXROM_JUMPTABLE_HOME_SIDE     ; must precede the INCLUDE
                                         ; below — selects the `jp`-
                                         ; emitting branch of KTAB_LIST
                                         ; rather than the EQU-emitting
                                         ; one exrom_build.asm gets
    INCLUDE "include/exrom_jumptable.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START

    DS   $0038 - $, $FF
; ---- RST 38 / IM 1 maskable interrupt entry point ----
; Same real keyboard-scan ISR as rom/test_basic.asm -- see kernel/
; interrupt/interrupt.asm's own header.
RST_38:
    call KBD_ISR_TICK
    ei
    reti

; ---- EXROM call table -- single source of truth is include/
; exrom_jumptable.inc's own KTAB_LIST macro; mirrors rom/test_basic.asm's
; own layout exactly (see that file if this drifts again). Needed here
; because basic.asm's BASIC_RUN calls BASIC_FULL_CHECK_EXROM
; unconditionally -- without this table (and a real exrom.bin
; paired via --rom-ts2068-1) the checker pages into garbage the moment
; RUN is pressed. ----
    ORG  KTAB_BASE
    KTAB_LIST
    ASSERT $ <= KTAB_END
    DB   KTAB_MAGIC

    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT
    call KBD_ISR_INIT                ; kernel/interrupt -- must run
                                     ; before the EI below

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though 15 real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ; (Superseded-but-harmless as of BASIC_COMMAND_LOOP's own later
    ; fix, which now counts real existing statements itself on every
    ; entry regardless of how they got into memory — this line's own
    ; value gets silently overwritten with the same correct count
    ; moments later. Left in for consistency with the tested,
    ; delivered state rather than removed.)
    ld   hl, 15
    ld   (CUR_EDIT_INDEX), hl

    im   1
    ei                                ; real interrupts now on -- see
                                     ; rom/test_basic.asm's own COLD_
                                     ; START comment for why

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $04,$00,$43,$4C,$53,$0D,$14,$00,$50,$52,$49,$4E,$54,$20,$22,$53
    DB   $50,$52,$49,$54,$45,$20,$44,$45,$4D,$4F,$22,$0D,$06,$00,$49,$4E
    DB   $4B,$20,$32,$0D,$13,$00,$42,$4C,$4F,$43,$4B,$20,$38,$2C,$38,$20
    DB   $54,$4F,$20,$31,$35,$2C,$31,$35,$0D,$16,$00,$53,$50,$52,$49,$54
    DB   $45,$20,$47,$52,$41,$42,$20,$30,$2C,$31,$2C,$31,$2C,$31,$2C,$31
    DB   $0D,$06,$00,$49,$4E,$4B,$20,$37,$0D,$04,$00,$43,$4C,$53,$0D,$14
    DB   $00,$50,$52,$49,$4E,$54,$20,$22,$53,$50,$52,$49,$54,$45,$20,$44
    DB   $45,$4D,$4F,$22,$0D,$10,$00,$46,$4F,$52,$20,$69,$20,$3D,$20,$30
    DB   $20,$54,$4F,$20,$32,$30,$0D,$13,$00,$53,$50,$52,$49,$54,$45,$20
    DB   $53,$48,$4F,$57,$20,$30,$2C,$31,$30,$2C,$69,$0D,$11,$00,$46,$4F
    DB   $52,$20,$64,$20,$3D,$20,$31,$20,$54,$4F,$20,$33,$30,$30,$0D,$07
    DB   $00,$4E,$45,$58,$54,$20,$64,$0D,$0E,$00,$53,$50,$52,$49,$54,$45
    DB   $20,$48,$49,$44,$45,$20,$30,$0D,$07,$00,$4E,$45,$58,$54,$20,$69
    DB   $0D,$0D,$00,$50,$52,$49,$4E,$54,$20,$22,$44,$4F,$4E,$45,$22,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here -- SAVE/LOAD
    ; now lives in EXROM (rom/exrom_storage.asm) and basic.asm's
    ; BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed address; this
    ; template never defined STORAGE_MATH_MULTIPLY16/STORAGE_MATH_DIVIDE16
    ; (storage.asm's required pre-INCLUDE EQUs), so including it here would
    ; never have assembled. See rom/test_basic.asm.
    INCLUDE "kernel/interrupt/interrupt.asm"
    INCLUDE "kernel/bank/bank.asm"

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_sprite_demo.bin", $0000, $4000
