; ============================================================================
; test_preload_testsqrdiv.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_testsqrdiv.asm TESTSQRDIV
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_testsqrdiv.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_testsqrdiv.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $04,$00,$43,$4C,$53,$0D,$0E,$00,$50,$52,$49,$4E,$54,$20,$53,$51
    DB   $52,$28,$31,$36,$29,$0D,$0E,$00,$50,$52,$49,$4E,$54,$20,$53,$51
    DB   $52,$28,$31,$35,$29,$0D,$0D,$00,$50,$52,$49,$4E,$54,$20,$53,$51
    DB   $52,$28,$30,$29,$0D,$0E,$00,$50,$52,$49,$4E,$54,$20,$53,$51,$52
    DB   $28,$2D,$35,$29,$0D,$11,$00,$50,$52,$49,$4E,$54,$20,$53,$51,$52
    DB   $28,$33,$32,$37,$36,$37,$29,$0D,$10,$00,$50,$52,$49,$4E,$54,$20
    DB   $44,$49,$56,$28,$31,$37,$2C,$35,$29,$0D,$11,$00,$50,$52,$49,$4E
    DB   $54,$20,$44,$49,$56,$28,$2D,$31,$37,$2C,$35,$29,$0D,$11,$00,$50
    DB   $52,$49,$4E,$54,$20,$44,$49,$56,$28,$31,$30,$30,$2C,$30,$29,$0D
    DB   $16,$00,$50,$52,$49,$4E,$54,$20,$53,$51,$52,$28,$44,$49,$56,$28
    DB   $31,$30,$30,$2C,$34,$29,$29,$0D,$1F,$00,$50,$52,$49,$4E,$54,$20
    DB   $44,$49,$56,$28,$4D,$4F,$44,$28,$31,$37,$2C,$35,$29,$2C,$31,$29
    DB   $2B,$53,$51,$52,$28,$31,$36,$29,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_testsqrdiv.bin", $0000, $4000
