; ============================================================================
; test_preload_scroll20.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_scroll20.asm SCROLL20
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_scroll20.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_scroll20.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though 20 real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ld   hl, 20
    ld   (CUR_EDIT_INDEX), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31,$22
    DB   $0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$32
    DB   $22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20
    DB   $33,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45
    DB   $20,$34,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E
    DB   $45,$20,$35,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49
    DB   $4E,$45,$20,$36,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22,$4C
    DB   $49,$4E,$45,$20,$37,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20,$22
    DB   $4C,$49,$4E,$45,$20,$38,$22,$0D,$0F,$00,$50,$52,$49,$4E,$54,$20
    DB   $22,$4C,$49,$4E,$45,$20,$39,$22,$0D,$10,$00,$50,$52,$49,$4E,$54
    DB   $20,$22,$4C,$49,$4E,$45,$20,$31,$30,$22,$0D,$10,$00,$50,$52,$49
    DB   $4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31,$31,$22,$0D,$10,$00,$50
    DB   $52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31,$32,$22,$0D,$10
    DB   $00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31,$33,$22
    DB   $0D,$10,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31
    DB   $34,$22,$0D,$10,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45
    DB   $20,$31,$35,$22,$0D,$10,$00,$50,$52,$49,$4E,$54,$20,$22,$4C,$49
    DB   $4E,$45,$20,$31,$36,$22,$0D,$10,$00,$50,$52,$49,$4E,$54,$20,$22
    DB   $4C,$49,$4E,$45,$20,$31,$37,$22,$0D,$10,$00,$50,$52,$49,$4E,$54
    DB   $20,$22,$4C,$49,$4E,$45,$20,$31,$38,$22,$0D,$10,$00,$50,$52,$49
    DB   $4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$31,$39,$22,$0D,$10,$00,$50
    DB   $52,$49,$4E,$54,$20,$22,$4C,$49,$4E,$45,$20,$32,$30,$22,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_scroll20.bin", $0000, $4000
