; ============================================================================
; test_preload_isolate_b.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_isolate_b.asm ISOLATEB
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_isolate_b.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_isolate_b.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $1E,$00,$43,$4C,$53,$3A,$20,$42,$4F,$52,$44,$45,$52,$20,$30,$3A
    DB   $20,$50,$41,$50,$45,$52,$20,$30,$3A,$20,$49,$4E,$4B,$20,$37,$0D
    DB   $2B,$00,$41,$54,$20,$35,$2C,$30,$3A,$20,$50,$52,$49,$4E,$54,$20
    DB   $22,$52,$6F,$77,$20,$35,$20,$73,$74,$61,$79,$73,$20,$77,$68,$69
    DB   $74,$65,$20,$6F,$6E,$20,$62,$6C,$61,$63,$6B,$22,$0D,$0F,$00,$50
    DB   $41,$50,$45,$52,$20,$37,$3A,$20,$49,$4E,$4B,$20,$30,$0D,$47,$00
    DB   $41,$54,$20,$34,$2C,$32,$30,$3A,$20,$50,$52,$49,$4E,$54,$20,$22
    DB   $54,$68,$69,$73,$20,$6C,$69,$6E,$65,$20,$69,$73,$20,$64,$65,$6C
    DB   $69,$62,$65,$72,$61,$74,$65,$6C,$79,$20,$77,$61,$79,$20,$74,$6F
    DB   $6F,$20,$6C,$6F,$6E,$67,$20,$66,$6F,$72,$20,$74,$68,$65,$20,$73
    DB   $63,$72,$65,$65,$6E,$22,$0D,$05,$00,$53,$54,$4F,$50,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_isolate_b.bin", $0000, $4000
