; ============================================================================
; test_preload_mode64_shapes.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_mode64_shapes.asm MODE64SHP
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_mode64_shapes.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_mode64_shapes.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $1E,$00,$43,$4C,$53,$3A,$20,$42,$4F,$52,$44,$45,$52,$20,$30,$3A
    DB   $20,$50,$41,$50,$45,$52,$20,$30,$3A,$20,$49,$4E,$4B,$20,$37,$0D
    DB   $12,$00,$4D,$4F,$44,$45,$20,$32,$3A,$20,$50,$41,$4C,$45,$54,$54
    DB   $45,$20,$30,$0D,$14,$00,$4C,$49,$4E,$45,$20,$30,$2C,$30,$20,$54
    DB   $4F,$20,$35,$31,$31,$2C,$31,$39,$31,$0D,$18,$00,$42,$4C,$4F,$43
    DB   $4B,$20,$32,$34,$30,$2C,$38,$30,$20,$54,$4F,$20,$32,$37,$30,$2C
    DB   $31,$30,$30,$0D,$11,$00,$43,$49,$52,$43,$4C,$45,$20,$32,$35,$36
    DB   $2C,$39,$36,$2C,$38,$30,$0D,$11,$00,$41,$3D,$50,$4F,$49,$4E,$54
    DB   $28,$35,$31,$31,$2C,$31,$39,$31,$29,$0D,$10,$00,$42,$3D,$50,$4F
    DB   $49,$4E,$54,$28,$33,$33,$36,$2C,$39,$36,$29,$0D,$07,$00,$4D,$4F
    DB   $44,$45,$20,$30,$0D,$0C,$00,$49,$46,$20,$41,$3D,$31,$20,$54,$48
    DB   $45,$4E,$0D,$29,$00,$41,$54,$20,$32,$30,$2C,$30,$3A,$20,$50,$52
    DB   $49,$4E,$54,$20,$22,$31,$29,$20,$6C,$69,$6E,$65,$20,$65,$6E,$64
    DB   $70,$6F,$69,$6E,$74,$20,$2D,$20,$50,$41,$53,$53,$22,$0D,$05,$00
    DB   $45,$4C,$53,$45,$0D,$29,$00,$41,$54,$20,$32,$30,$2C,$30,$3A,$20
    DB   $50,$52,$49,$4E,$54,$20,$22,$31,$29,$20,$6C,$69,$6E,$65,$20,$65
    DB   $6E,$64,$70,$6F,$69,$6E,$74,$20,$2D,$20,$46,$41,$49,$4C,$22,$0D
    DB   $07,$00,$45,$4E,$44,$20,$49,$46,$0D,$0C,$00,$49,$46,$20,$42,$3D
    DB   $31,$20,$54,$48,$45,$4E,$0D,$2A,$00,$41,$54,$20,$32,$31,$2C,$30
    DB   $3A,$20,$50,$52,$49,$4E,$54,$20,$22,$32,$29,$20,$63,$69,$72,$63
    DB   $6C,$65,$20,$72,$69,$67,$68,$74,$20,$20,$20,$2D,$20,$50,$41,$53
    DB   $53,$22,$0D,$05,$00,$45,$4C,$53,$45,$0D,$2A,$00,$41,$54,$20,$32
    DB   $31,$2C,$30,$3A,$20,$50,$52,$49,$4E,$54,$20,$22,$32,$29,$20,$63
    DB   $69,$72,$63,$6C,$65,$20,$72,$69,$67,$68,$74,$20,$20,$20,$2D,$20
    DB   $46,$41,$49,$4C,$22,$0D,$07,$00,$45,$4E,$44,$20,$49,$46,$0D,$05
    DB   $00,$53,$54,$4F,$50,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_mode64_shapes.bin", $0000, $4000
