; ============================================================================
; test_preload_round1.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_round1.asm ROUND1TEST
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_round1.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_round1.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START
    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $1E,$00,$43,$4C,$53,$3A,$20,$42,$4F,$52,$44,$45,$52,$20,$30,$3A
    DB   $20,$50,$41,$50,$45,$52,$20,$30,$3A,$20,$49,$4E,$4B,$20,$37,$0D
    DB   $23,$00,$41,$54,$20,$30,$2C,$30,$3A,$20,$50,$52,$49,$4E,$54,$20
    DB   $22,$4E,$6F,$72,$6D,$61,$6C,$20,$49,$4E,$4B,$20,$37,$20,$28,$64
    DB   $69,$6D,$29,$22,$0D,$09,$00,$42,$52,$49,$47,$48,$54,$20,$31,$0D
    DB   $26,$00,$41,$54,$20,$31,$2C,$30,$3A,$20,$50,$52,$49,$4E,$54,$20
    DB   $22,$42,$52,$49,$47,$48,$54,$20,$49,$4E,$4B,$20,$37,$20,$28,$62
    DB   $72,$69,$67,$68,$74,$29,$22,$0D,$09,$00,$42,$52,$49,$47,$48,$54
    DB   $20,$30,$0D,$26,$00,$41,$54,$20,$33,$2C,$30,$3A,$20,$50,$52,$49
    DB   $4E,$54,$20,$22,$4C,$6F,$6E,$67,$20,$6C,$69,$6E,$65,$20,$74,$65
    DB   $73,$74,$20,$62,$65,$6C,$6F,$77,$3A,$22,$0D,$47,$00,$41,$54,$20
    DB   $34,$2C,$32,$30,$3A,$20,$50,$52,$49,$4E,$54,$20,$22,$54,$68,$69
    DB   $73,$20,$6C,$69,$6E,$65,$20,$69,$73,$20,$64,$65,$6C,$69,$62,$65
    DB   $72,$61,$74,$65,$6C,$79,$20,$77,$61,$79,$20,$74,$6F,$6F,$20,$6C
    DB   $6F,$6E,$67,$20,$66,$6F,$72,$20,$74,$68,$65,$20,$73,$63,$72,$65
    DB   $65,$6E,$22,$0D,$2E,$00,$41,$54,$20,$36,$2C,$30,$3A,$20,$50,$52
    DB   $49,$4E,$54,$20,$22,$63,$75,$74,$73,$20,$6F,$66,$66,$2C,$20,$6E
    DB   $6F,$74,$68,$69,$6E,$67,$20,$65,$6C,$73,$65,$20,$62,$72,$6F,$6B
    DB   $65,$6E,$22,$0D,$07,$00,$4D,$4F,$44,$45,$20,$31,$0D,$0A,$00,$43
    DB   $50,$4C,$4F,$54,$20,$30,$2C,$30,$0D,$0A,$00,$43,$50,$4C,$4F,$54
    DB   $20,$31,$2C,$30,$0D,$0A,$00,$43,$50,$4C,$4F,$54,$20,$30,$2C,$31
    DB   $0D,$0A,$00,$43,$50,$4C,$4F,$54,$20,$31,$2C,$31,$0D,$05,$00,$53
    DB   $54,$4F,$50,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_round1.bin", $0000, $4000
