; ============================================================================
; test_preload_for_next.asm — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> test_preload_for_next.asm FORNEXT
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus test_preload_for_next.asm
; Run:
;   fuse --machine ts2068 --rom-ts2068-0 test_preload_for_next.bin --rom-ts2068-1 rom1.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START

    DS   $0038 - $, $FF
; ---- RST 38 / IM 1 maskable interrupt entry point ----
; Same real keyboard-scan ISR as rom/test_basic.asm -- see kernel/
; interrupt/interrupt.asm's own header.
RST_38:
    call KBD_ISR_TICK
    ei
    reti

    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT
    call KBD_ISR_INIT                ; kernel/interrupt -- must run
                                     ; before the EI below

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though 38 real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ; (Superseded-but-harmless as of BASIC_COMMAND_LOOP's own later
    ; fix, which now counts real existing statements itself on every
    ; entry regardless of how they got into memory — this line's own
    ; value gets silently overwritten with the same correct count
    ; moments later. Left in for consistency with the tested,
    ; delivered state rather than removed.)
    ld   hl, 38
    ld   (CUR_EDIT_INDEX), hl

    im   1
    ei                                ; real interrupts now on -- see
                                     ; rom/test_basic.asm's own COLD_
                                     ; START comment for why

    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally

PRELOAD_DATA:
    DB   $1D,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$31,$3A,$20,$45,$58,$50
    DB   $45,$43,$54,$20,$31,$20,$32,$20,$33,$20,$34,$20,$35,$22,$0D,$0F
    DB   $00,$46,$4F,$52,$20,$49,$20,$3D,$20,$31,$20,$54,$4F,$20,$35,$0D
    DB   $08,$00,$50,$52,$49,$4E,$54,$20,$49,$0D,$07,$00,$4E,$45,$58,$54
    DB   $20,$49,$0D,$20,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$32,$3A,$20
    DB   $45,$58,$50,$45,$43,$54,$20,$30,$20,$32,$20,$34,$20,$36,$20,$38
    DB   $20,$31,$30,$22,$0D,$17,$00,$46,$4F,$52,$20,$49,$20,$3D,$20,$30
    DB   $20,$54,$4F,$20,$31,$30,$20,$53,$54,$45,$50,$20,$32,$0D,$08,$00
    DB   $50,$52,$49,$4E,$54,$20,$49,$0D,$07,$00,$4E,$45,$58,$54,$20,$49
    DB   $0D,$1D,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$33,$3A,$20,$45,$58
    DB   $50,$45,$43,$54,$20,$35,$20,$34,$20,$33,$20,$32,$20,$31,$22,$0D
    DB   $17,$00,$46,$4F,$52,$20,$49,$20,$3D,$20,$35,$20,$54,$4F,$20,$31
    DB   $20,$53,$54,$45,$50,$20,$2D,$31,$0D,$08,$00,$50,$52,$49,$4E,$54
    DB   $20,$49,$0D,$07,$00,$4E,$45,$58,$54,$20,$49,$0D,$27,$00,$50,$52
    DB   $49,$4E,$54,$20,$22,$54,$34,$3A,$20,$45,$58,$50,$45,$43,$54,$20
    DB   $53,$4B,$49,$50,$20,$4F,$4B,$2C,$20,$4E,$4F,$20,$4E,$55,$4D,$42
    DB   $45,$52,$53,$22,$0D,$0F,$00,$46,$4F,$52,$20,$49,$20,$3D,$20,$35
    DB   $20,$54,$4F,$20,$31,$0D,$08,$00,$50,$52,$49,$4E,$54,$20,$49,$0D
    DB   $07,$00,$4E,$45,$58,$54,$20,$49,$0D,$10,$00,$50,$52,$49,$4E,$54
    DB   $20,$22,$53,$4B,$49,$50,$20,$4F,$4B,$22,$0D,$25,$00,$50,$52,$49
    DB   $4E,$54,$20,$22,$54,$35,$3A,$20,$45,$58,$50,$45,$43,$54,$20,$31
    DB   $31,$20,$31,$32,$20,$31,$33,$20,$32,$31,$20,$32,$32,$20,$32,$33
    DB   $22,$0D,$0F,$00,$46,$4F,$52,$20,$49,$20,$3D,$20,$31,$20,$54,$4F
    DB   $20,$32,$0D,$0F,$00,$46,$4F,$52,$20,$4A,$20,$3D,$20,$31,$20,$54
    DB   $4F,$20,$33,$0D,$0D,$00,$50,$52,$49,$4E,$54,$20,$49,$2A,$31,$30
    DB   $2B,$4A,$0D,$07,$00,$4E,$45,$58,$54,$20,$4A,$0D,$07,$00,$4E,$45
    DB   $58,$54,$20,$49,$0D,$25,$00,$50,$52,$49,$4E,$54,$20,$22,$54,$36
    DB   $3A,$20,$45,$58,$50,$45,$43,$54,$20,$31,$20,$32,$20,$33,$20,$28
    DB   $42,$41,$52,$45,$20,$4E,$45,$58,$54,$29,$22,$0D,$0F,$00,$46,$4F
    DB   $52,$20,$49,$20,$3D,$20,$31,$20,$54,$4F,$20,$33,$0D,$08,$00,$50
    DB   $52,$49,$4E,$54,$20,$49,$0D,$05,$00,$4E,$45,$58,$54,$0D,$24,$00
    DB   $50,$52,$49,$4E,$54,$20,$22,$54,$37,$3A,$20,$45,$58,$50,$45,$43
    DB   $54,$20,$30,$20,$28,$53,$54,$45,$50,$20,$30,$20,$47,$55,$41,$52
    DB   $44,$29,$22,$0D,$06,$00,$58,$20,$3D,$20,$30,$0D,$16,$00,$46,$4F
    DB   $52,$20,$49,$20,$3D,$20,$31,$20,$54,$4F,$20,$31,$20,$53,$54,$45
    DB   $50,$20,$30,$0D,$0A,$00,$58,$20,$3D,$20,$58,$20,$2B,$20,$31,$0D
    DB   $0E,$00,$49,$46,$20,$58,$20,$3E,$20,$33,$20,$54,$48,$45,$4E,$0D
    DB   $0F,$00,$47,$4F,$54,$4F,$20,$53,$54,$45,$50,$30,$44,$4F,$4E,$45
    DB   $0D,$07,$00,$45,$4E,$44,$20,$49,$46,$0D,$07,$00,$4E,$45,$58,$54
    DB   $20,$49,$0D,$0B,$00,$53,$54,$45,$50,$30,$44,$4F,$4E,$45,$3A,$0D
    DB   $08,$00,$50,$52,$49,$4E,$54,$20,$58,$0D,$17,$00,$50,$52,$49,$4E
    DB   $54,$20,$22,$41,$4C,$4C,$20,$54,$45,$53,$54,$53,$20,$44,$4F,$4E
    DB   $45,$22,$0D
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    INCLUDE "kernel/editor/editor.asm"
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    ; kernel/storage/storage.asm intentionally NOT included here (2026-08-19
    ; cleanup) -- SAVE/LOAD now lives in EXROM (rom/exrom_storage.asm) and
    ; basic.asm's BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed
    ; address; this file never defined STORAGE_MATH_MULTIPLY16/
    ; STORAGE_MATH_DIVIDE16 (storage.asm's required pre-INCLUDE EQUs), so this
    ; line would never have assembled anyway. See rom/test_basic.asm.
    INCLUDE "kernel/interrupt/interrupt.asm"

    DS   $4000 - $, $FF

    SAVEBIN "test_preload_for_next.bin", $0000, $4000
