#!/usr/bin/env python3
"""
tools/preload_gen.py — encodes a plain-text BASIC program listing into
this ROM's exact program-area storage format, and emits a ready-to-
assemble .asm test harness that pre-loads it into RAM at boot (no
typing, no SAVE/LOAD tape mechanism needed).

Storage format (see kernel/memory/memory.asm's own header, "line
storage format" — this script mirrors it exactly, byte for byte):
    each statement = [length: 2 bytes, little-endian][content bytes]
                      [terminator: 1 byte, $0D]
    length = len(content) + 1 (the +1 counts the terminator byte,
    matching BASIC_TOKENIZE_LINE's own "B=content length; A=B+1" step
    in basic/basic.asm)
Statements are simply concatenated back to back — no line numbers, no
pointers between them, matching how kernel/memory actually walks the
program area (MEM_LINE_FIRST/MEM_LINE_NEXT just add [length]+2 to
advance).

Keyword matching is case-insensitive at both parse and display time
(BASIC_MATCH_KEYWORD / BASIC_TRY_DETECT_ONE both uppercase each
character before comparing), so the source text here can be typed in
any case and will execute and highlight identically to text that was
typed and committed normally through the editor — this script does
NOT need to replicate BASIC_UPPERCASE_KEYWORD_PREFIX's own storage-
mutation step, only the length-prefix framing.

Usage:
    python3 tools/preload_gen.py <program.txt> <output.asm> [PROGNAME] [--autorun]

<program.txt>: one BASIC statement per line, plain text, blank lines
and lines starting with ';;' are skipped (comments for the LISTING
file itself, not stored as REM statements in the program — use REM
directly in a program line if you want an in-program comment).

Output: a standalone rom/*.asm file, assembled and run exactly like
rom/test_basic.asm (same COLD_START shape, same modules included) —
the only difference is a few extra instructions at boot that copy the
encoded program into RAM at PROG_AREA_START and set PROG_END, BEFORE
handing control to the normal BASIC_COMMAND_LOOP. The program shows up
already sitting in the editor, exactly as if it had just been typed
and committed line by line — LIST/RUN/edit/navigate all work normally
from there.

--autorun (2026-08-22): skips the editor entirely and calls BASIC_RUN
directly at boot, then hangs (`jr $`). Border color is the pass/fail
signal, this project's own established convention (no serial/stdout on
real hardware) — but split into two independent layers, so a self-
checking BASIC program's own result is never confused with a harness-
level problem:
  - YELLOW ($06): the whole-program static check failed (CHECK_ERROR_
    COUNT nonzero) — BASIC_RUN never actually ran the program at all.
    A malformed statement, not a real test failure.
  - otherwise: BASIC_RUN executed normally, and whatever border color
    the PROGRAM ITSELF last set (via its own `BORDER` statement) is
    left showing — this is the real self-checking test's own verdict.
    Every autorun program in this suite ends with `IF <fail-count> = 0
    THEN BORDER 4 : IF <fail-count> > 0 THEN BORDER 2` (green=pass,
    red=fail), matching every hand-written test in this project before
    it. Without --autorun, the harness instead drops into the normal
    interactive editor (BASIC_COMMAND_LOOP) exactly as before — the
    default, unchanged.
"""
import sys


def encode_program(lines):
    """Returns the raw bytes for the whole program area, in this
    project's [len:2][content][$0D] concatenated format."""
    out = bytearray()
    for line in lines:
        content = line.encode('ascii')
        if len(content) > 126:
            raise ValueError(
                f"statement too long ({len(content)} chars, max 126 -- "
                f"matches EDIT_LINE_BUF_LEN-1, the same limit typing "
                f"the line by hand would hit): {line!r}")
        length = len(content) + 1  # +1 for the $0D terminator
        out += bytes([length & 0xFF, (length >> 8) & 0xFF])
        out += content
        out += b'\x0D'
    return bytes(out)


def to_db_lines(data, per_line=16):
    """Formats raw bytes as sjasmplus DB directives, this project's
    established data-listing style (see basic/basic.asm's KW_* strings
    for the convention this follows -- though those are ASCII DB
    strings; this is raw hex since the content includes non-printable
    length-prefix bytes and the $0D terminator)."""
    out = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        out.append('    DB   ' + ','.join(f'${b:02X}' for b in chunk))
    return out


HARNESS_TEMPLATE = '''; ============================================================================
; {outname} — pre-loaded BASIC program, generated by tools/preload_gen.py
;
; NOT hand-written -- regenerate via:
;   python3 tools/preload_gen.py <program.txt> {outname} {progname}
; from the plain-text listing, rather than hand-editing PRELOAD_DATA
; below. Same COLD_START shape as rom/test_basic.asm, with one extra
; step before BASIC_COMMAND_LOOP: copy PRELOAD_DATA into RAM at
; PROG_AREA_START and set PROG_END past it. From the user's
; perspective this is indistinguishable from having typed the program
; in and pressed ENTER after every line -- LIST/RUN/edit/navigate all
; work normally, no SAVE/LOAD tape step needed to get it into memory.
;
; Build:
;   sjasmplus {outname}
; Run: (needs a real exrom.bin now -- see rom/exrom_build.asm -- the
; checker AND storage this file's own basic.asm INCLUDE pulls in both
; page there unconditionally on RUN/SAVE/LOAD; a placeholder rom1.bin
; pages into garbage)
;   sjasmplus rom/exrom_build.asm
;   fuse --machine ts2068 --rom-ts2068-0 {binname} --rom-ts2068-1 exrom.bin
; ============================================================================

    INCLUDE "include/hardware.inc"
    INCLUDE "include/sysvars.inc"
    DEFINE EXROM_JUMPTABLE_HOME_SIDE     ; must precede the INCLUDE
                                         ; below — selects the `jp`-
                                         ; emitting branch of KTAB_LIST
                                         ; rather than the EQU-emitting
                                         ; one exrom_build.asm gets
    INCLUDE "include/exrom_jumptable.inc"

    DEVICE NOSLOT64K

    ORG $0000
RST_00:
    di
    jp   COLD_START

    DS   $0028 - $, $FF
; ---- RST 28: calculator engine entry point -- matches rom/test_basic.
; asm's own wiring exactly (added here 2026-08-22 after a preload-
; harness "hang" investigating a SIN()/PI() bug turned out to be THIS
; gap instead: with no RST_28 defined, the DS padding above used to
; fill $0028 with $FF -- opcode for RST $38 -- so any `rst $28` in a
; harness generated before this fix silently jumped into the keyboard
; ISR entry instead of the calculator engine, not a real product bug).
; MUST be a bare `jp`, not `call` -- see basic/basic.asm's CALC_ENTRY_
; TRAMPOLINE header for why (RST pushed the literal-op byte stream's
; address as the return address; the calculator needs that exact value
; untouched on top of the stack). ----
RST_28:
    jp   CALC_ENTRY_TRAMPOLINE

    DS   $0038 - $, $FF
; ---- RST 38 / IM 1 maskable interrupt entry point ----
; Same real keyboard-scan ISR as rom/test_basic.asm -- see kernel/
; interrupt/interrupt.asm's own header.
RST_38:
    call KBD_ISR_TICK
    ei
    reti

; ---- EXROM call table -- single source of truth is include/
; exrom_jumptable.inc's own KTAB_LIST macro; mirrors rom/test_basic.asm's
; own layout exactly (see that file if this drifts again). Needed here
; because basic.asm's BASIC_RUN calls BASIC_FULL_CHECK_EXROM
; unconditionally -- without this table (and a real exrom.bin
; paired via --rom-ts2068-1) the checker pages into garbage the moment
; RUN is pressed. ----
    ORG  KTAB_BASE
    KTAB_LIST
    ASSERT $ <= KTAB_END
    DB   KTAB_MAGIC

    DS   $0100 - $, $FF

COLD_START:
    ld   sp, $FF00
    call MEM_INIT
    call KBD_ISR_INIT                ; kernel/interrupt -- must run
                                     ; before the EI below

    ; copy the pre-encoded program into the program area, then set
    ; PROG_END past it -- same effect as MEM_LINE_STORE appending each
    ; statement one at a time via the editor, just done in one shot
    ld   hl, PRELOAD_DATA
    ld   de, PROG_AREA_START
    ld   bc, PRELOAD_LEN
    ldir
    ld   hl, PROG_AREA_START + PRELOAD_LEN
    ld   (PROG_END), hl

    ; CUR_EDIT_INDEX must also reflect the real statement count here —
    ; normally MEM_LINE_STORE's own "appending a new statement" path
    ; in basic.asm increments it once per commit, so by the time N
    ; statements exist it correctly reads N. This harness bypasses
    ; that entirely (one bulk copy instead of N individual commits),
    ; so without this line CUR_EDIT_INDEX stays at its cold-boot
    ; default of 0 even though {stmt_count} real statements now exist
    ; — every scroll-boundary check downstream (BASIC_HANDLE_NAV's
    ; own tail, and BASIC_REDRAW_PROGRAM's auto-scroll) reads
    ; CUR_EDIT_INDEX directly, so a wrong starting value here silently
    ; broke scroll-trigger testing for any preload-based test that
    ; then typed further lines by hand. Found via a debug.bin dump
    ; showing CUR_EDIT_INDEX=3 (0 + 3 manually-typed appends) instead
    ; of the expected 23 after loading 20 preloaded + typing 3 more.
    ; (Superseded-but-harmless as of BASIC_COMMAND_LOOP's own later
    ; fix, which now counts real existing statements itself on every
    ; entry regardless of how they got into memory — this line's own
    ; value gets silently overwritten with the same correct count
    ; moments later. Left in for consistency with the tested,
    ; delivered state rather than removed.)
    ld   hl, {stmt_count}
    ld   (CUR_EDIT_INDEX), hl

    im   1
    ei                                ; real interrupts now on -- see
                                     ; rom/test_basic.asm's own COLD_
                                     ; START comment for why

{run_tail}
PRELOAD_DATA:
{db_lines}
PRELOAD_LEN EQU $ - PRELOAD_DATA

    INCLUDE "basic/basic.asm"
    ; kernel/editor/editor.asm intentionally NOT included here (2026-
    ; 08-22) -- the editor moved whole to EXROM (rom/exrom_editor.asm);
    ; basic.asm's own BASIC_EDITOR_*_EXROM wrappers reach it via fixed
    ; EXROM entry stubs instead. A real exrom.bin (built the same way
    ; RUN/SAVE/LOAD already require) is now needed just to bring up the
    ; editor, not only to RUN/SAVE/LOAD -- see this file's own Run: note.
    INCLUDE "kernel/memory/memory.asm"
    INCLUDE "kernel/io/io.asm"
    INCLUDE "kernel/graphics/graphics.asm"
    INCLUDE "kernel/math/math.asm"
    INCLUDE "kernel/sound/sound.asm"
    ; kernel/storage/storage.asm intentionally NOT included here -- SAVE/LOAD
    ; now lives in EXROM (rom/exrom_storage.asm) and basic.asm's
    ; BASIC_SAVE_EXROM/BASIC_LOAD_EXROM page there by fixed address; this
    ; template never defined STORAGE_MATH_MULTIPLY16/STORAGE_MATH_DIVIDE16
    ; (storage.asm's required pre-INCLUDE EQUs), so including it here would
    ; never have assembled. See rom/test_basic.asm.
    INCLUDE "kernel/interrupt/interrupt.asm"
    INCLUDE "kernel/bank/bank.asm"

    DS   $4000 - $, $FF

    SAVEBIN "{binname}", $0000, $4000
'''


RUN_TAIL_INTERACTIVE = '''    call BASIC_COMMAND_LOOP          ; never returns -- same entry
                                     ; point rom/test_basic.asm uses;
                                     ; the program is already sitting
                                     ; in the editor from here on,
                                     ; ready to LIST/RUN/edit normally
'''

RUN_TAIL_AUTORUN = '''    call BASIC_RUN                   ; --autorun: skip the editor,
                                     ; run the preloaded program
                                     ; directly -- see this script's
                                     ; own --autorun doc for the two-
                                     ; layer border-color convention
    ld   hl, (CHECK_ERROR_COUNT)
    ld   a, h
    or   l
    jr   z, .autorun_hang
    ld   a, 6                        ; YELLOW -- whole-program check
                                     ; failed, BASIC_RUN never ran the
                                     ; program at all
    call GFX_SET_BORDER
.autorun_hang:
    jr   .autorun_hang               ; otherwise: leave whatever
                                     ; border color the PROGRAM itself
                                     ; last set via its own BORDER
                                     ; statement -- that's the real
                                     ; self-checking test verdict
'''


def main():
    argv = [a for a in sys.argv[1:] if a != '--autorun']
    autorun = len(argv) != len(sys.argv) - 1
    if len(argv) < 2:
        print(__doc__)
        sys.exit(1)
    src_path = argv[0]
    out_path = argv[1]
    progname = argv[2] if len(argv) > 2 else 'PRELOADED'

    with open(src_path) as f:
        lines = [l.rstrip('\n') for l in f]
    lines = [l for l in lines if l.strip() and not l.strip().startswith(';;')]

    data = encode_program(lines)
    db_lines = '\n'.join(to_db_lines(data))

    outname = out_path.split('/')[-1]
    binname = outname.rsplit('.', 1)[0] + '.bin'

    text = HARNESS_TEMPLATE.format(
        outname=outname, binname=binname, progname=progname,
        db_lines=db_lines, stmt_count=len(lines),
        run_tail=RUN_TAIL_AUTORUN if autorun else RUN_TAIL_INTERACTIVE)

    with open(out_path, 'w') as f:
        f.write(text)

    print(f"Encoded {len(lines)} statement(s), {len(data)} bytes -> {out_path}")
    print(f"Build:  sjasmplus {out_path}")
    print(f"Build exrom.bin too: sjasmplus rom/exrom_build.asm")
    print(f"Run:    fuse --machine ts2068 --rom-ts2068-0 {binname} "
          f"--rom-ts2068-1 exrom.bin")
    if autorun:
        print("--autorun: runs immediately: YELLOW=check failed, "
              "otherwise the program's own final BORDER is the verdict")


if __name__ == '__main__':
    main()
